services:
  - type: web
    name: swarna-weda-madura-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SUPER_ADMIN_EMAILS
        sync: false
